name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Core:
    name: ${{ matrix.os }} - ${{ matrix.config_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        config_name: [Widgets, QML]
        include:
          - config_name: "Widgets"
            cmake_flags: "-DSIMPLE_MAP_VIEW_BUILD_TESTS=ON"
            build_type: "Debug"
          
          - config_name: "QML"
            cmake_flags: "-DSIMPLE_MAP_VIEW_BUILD_QML=ON -DSIMPLE_MAP_VIEW_BUILD_TESTS=ON"
            build_type: "Debug"

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Qt Environment
        uses: ./.github/actions/setup-qt-env
          
      - name: Configure CMake
        shell: bash
        run: |
          mkdir build
          cd build
          cmake .. ${{ matrix.cmake_flags }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        shell: bash
        working-directory: build
        run: |
          cmake --build . --config ${{ matrix.build_type }}

      - name: Run (Linux)
        if: runner.os == 'Linux'
        working-directory: build
        run: xvfb-run ctest --output-on-failure

      - name: Run (Windows / macOS)
        if: runner.os != 'Linux'
        shell: bash
        working-directory: build
        run: ctest -C ${{ matrix.build_type }} --output-on-failure

  Python:
    name: Python ${{ matrix.python-versions }} ${{ matrix.os }}
    needs: Core
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-versions: ['3.10', '3.11', '3.12', '3.13']
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Qt Environment
        uses: ./.github/actions/setup-qt-env

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install Bindings
        shell: bash
        env:
          PYTHONIOENCODING: utf-8
        run: pip install .

      - name: Run (Linux)
        if: runner.os == 'Linux'
        run: xvfb-run pytest

      - name: Run (Windows)
        if: runner.os != 'Linux'
        run: pytest